import type { MerchProduct } from "@carasta/types";

export const MOCK_MERCH: MerchProduct[] = [
  {
    id: "m-001",
    name: "Carasta Racing Hoodie",
    description: "Premium heavyweight hoodie with embroidered Carasta logo. 400gsm cotton-polyester blend.",
    category: "apparel",
    price: 89,
    compareAtPrice: 110,
    images: [
      { id: "m001-1", url: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&auto=format&fit=crop", alt: "Carasta Hoodie", isPrimary: true },
      { id: "m001-2", url: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&auto=format&fit=crop", alt: "Carasta Hoodie back" },
    ],
    variants: [
      { id: "mv-s", name: "Size", value: "S", inStock: true },
      { id: "mv-m", name: "Size", value: "M", inStock: true },
      { id: "mv-l", name: "Size", value: "L", inStock: true },
      { id: "mv-xl", name: "Size", value: "XL", inStock: false },
    ],
    tags: ["hoodie", "apparel", "racing"],
    inStock: true,
    stockCount: 42,
    rating: 4.8,
    reviewCount: 124,
    createdAt: "2023-06-01T00:00:00Z",
  },
  {
    id: "m-002",
    name: "Carasta Cap — Black",
    description: "Six-panel structured cap with metal buckle closure. One size fits most.",
    category: "accessories",
    price: 35,
    images: [
      { id: "m002-1", url: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop", alt: "Carasta Cap", isPrimary: true },
    ],
    variants: [{ id: "mv-os", name: "Size", value: "One Size", inStock: true }],
    tags: ["cap", "accessories"],
    inStock: true,
    stockCount: 89,
    rating: 4.6,
    reviewCount: 67,
    createdAt: "2023-06-01T00:00:00Z",
  },
  {
    id: "m-003",
    name: "Detailing Kit Pro",
    description: "Complete professional car detailing kit. Includes microfiber cloths, applicators, and ceramic spray.",
    category: "car-care",
    price: 149,
    images: [
      { id: "m003-1", url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop", alt: "Detailing Kit", isPrimary: true },
    ],
    variants: [{ id: "mv-std", name: "Type", value: "Standard", inStock: true }],
    tags: ["detailing", "car-care", "cleaning"],
    inStock: true,
    stockCount: 28,
    rating: 4.9,
    reviewCount: 203,
    createdAt: "2023-07-15T00:00:00Z",
  },
  {
    id: "m-004",
    name: "Scale Model — Porsche 911 GT3 RS",
    description: "1:18 scale die-cast model. Officially licensed. Comes in collector's display case.",
    category: "collectibles",
    price: 189,
    images: [
      { id: "m004-1", url: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop", alt: "Porsche Scale Model", isPrimary: true },
    ],
    variants: [
      { id: "mv-red", name: "Color", value: "Guards Red", inStock: true },
      { id: "mv-silver", name: "Color", value: "Silver", inStock: false },
    ],
    tags: ["collectibles", "model", "porsche"],
    inStock: true,
    stockCount: 12,
    rating: 5.0,
    reviewCount: 34,
    createdAt: "2023-08-01T00:00:00Z",
  },
  {
    id: "m-005",
    name: "Carasta Sticker Pack",
    description: "10 premium vinyl stickers. Waterproof and UV resistant. Mix of car culture designs.",
    category: "stickers",
    price: 18,
    images: [
      { id: "m005-1", url: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=800&auto=format&fit=crop", alt: "Sticker Pack", isPrimary: true },
    ],
    variants: [{ id: "mv-pack", name: "Pack", value: "10-Pack", inStock: true }],
    tags: ["stickers", "lifestyle"],
    inStock: true,
    stockCount: 200,
    rating: 4.7,
    reviewCount: 89,
    createdAt: "2023-05-01T00:00:00Z",
  },
  {
    id: "m-006",
    name: "Carasta T-Shirt — White",
    description: "Premium Pima cotton t-shirt. Minimal Carasta wordmark on chest. Perfect for car meets.",
    category: "apparel",
    price: 45,
    images: [
      { id: "m006-1", url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop", alt: "Carasta T-Shirt", isPrimary: true },
    ],
    variants: [
      { id: "mv-s2", name: "Size", value: "S", inStock: true },
      { id: "mv-m2", name: "Size", value: "M", inStock: true },
      { id: "mv-l2", name: "Size", value: "L", inStock: true },
    ],
    tags: ["tshirt", "apparel"],
    inStock: true,
    stockCount: 156,
    rating: 4.5,
    reviewCount: 234,
    createdAt: "2023-04-01T00:00:00Z",
  },
];
