import type { Notification } from "@carasta/types";

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n-001",
    type: "outbid",
    title: "You've been outbid",
    message: "Someone placed a higher bid of $90,000 on 2019 Porsche 911 Carrera S",
    isRead: false,
    actionUrl: "/auctions/a-001",
    metadata: { auctionId: "a-001", vehicleId: "v-001", bidAmount: 90000 },
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "n-002",
    type: "auction-ending",
    title: "Auction ending soon",
    message: "1969 Ford Mustang Boss 429 auction ends in 30 minutes",
    isRead: false,
    actionUrl: "/auctions/a-003",
    metadata: { auctionId: "a-003", vehicleId: "v-003" },
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "n-003",
    type: "follower",
    title: "New follower",
    message: "Alex Carter started following you",
    isRead: false,
    actionUrl: "/profile/alex_motors",
    metadata: { userId: "user-1" },
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "n-004",
    type: "like",
    title: "New like",
    message: "Marco Rossi liked your post",
    isRead: true,
    actionUrl: "/community",
    metadata: { userId: "user-3", postId: "p-001" },
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "n-005",
    type: "auction-won",
    title: "Congratulations! You won!",
    message: "You won the 2020 Toyota GR Supra 3.0 for $56,500",
    isRead: true,
    actionUrl: "/profile/purchases",
    metadata: { auctionId: "a-012", vehicleId: "v-007", bidAmount: 56500 },
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "n-006",
    type: "comment",
    title: "New comment",
    message: "Priya Singh commented on your post: \"Absolutely gorgeous!\"",
    isRead: true,
    actionUrl: "/community",
    metadata: { userId: "user-2", postId: "p-001" },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "n-007",
    type: "new-bid",
    title: "New bid on your listing",
    message: "A new bid of $84,000 was placed on 2016 Porsche Cayman GT4",
    isRead: true,
    actionUrl: "/sell/listings",
    metadata: { auctionId: "a-006", vehicleId: "v-008", bidAmount: 84000 },
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "n-008",
    type: "system",
    title: "Identity verified",
    message: "Your account has been verified. You can now bid on all auctions.",
    isRead: true,
    createdAt: new Date(Date.now() - 604800000).toISOString(),
  },
];
