import type { Vehicle } from "@carasta/types";
import { MOCK_USERS } from "./users";

const u1 = MOCK_USERS[0]!;
const u2 = MOCK_USERS[1]!;
const u3 = MOCK_USERS[2]!;
const u4 = MOCK_USERS[3]!;

const img = (id: string, alt: string, isPrimary = false) => ({
  id: `${id}-${alt.replace(/\s+/g, "-").toLowerCase()}`,
  url: `https://images.unsplash.com/photo-${id}?w=1200&auto=format&fit=crop`,
  alt,
  isPrimary,
});

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "v-001",
    title: "1969 Ford Mustang Boss 429",
    slug: "1969-ford-mustang-boss-429",
    spec: { make: "Ford", model: "Mustang", year: 1969, trim: "Boss 429", engineSize: "7.0L V8", horsepower: 375, torque: 450, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 52400, exteriorColor: "Candyapple Red", interiorColor: "Black", vin: "9F02Z195780", doors: 2, seats: 4, bodyStyle: "Fastback" },
    condition: "excellent",
    status: "in-auction",
    description: "Numbers-matching 1969 Boss 429 finished in Candyapple Red. Rotisserie restoration completed with a full Marti Report and original drivetrain. One of the most sought-after muscle cars ever built.",
    story: "I spent fifteen years chasing this car. Frame-off restoration by a certified shop, correct down to the hose clamps. It's time to pass it on to the next caretaker.",
    images: [
      img("1572011440385-cf32f4fc7d02", "Ford Mustang Boss 429 front", true),
      img("1584345274849-e9596d6ea12d", "Mustang side profile"),
    ],
    location: { city: "Detroit", state: "MI", country: "US", zip: "48201" },
    seller: u4,
    features: ["Numbers Matching", "Marti Report", "Rotisserie Restoration", "Original 429 V8", "4-Speed Toploader", "Magnum 500 Wheels"],
    reservePrice: 145000,
    startingPrice: 110000,
    estimatedValue: 165000,
    hasInspectionReport: true,
    hasFinancingOptions: false,
    views: 3210,
    watchlistCount: 201,
    createdAt: "2024-01-12T08:00:00Z",
    updatedAt: "2024-01-20T15:30:00Z",
  },
  {
    id: "v-002",
    title: "1963 Jaguar E-Type Series 1 3.8 Coupe",
    slug: "1963-jaguar-e-type-series-1-38-coupe",
    spec: { make: "Jaguar", model: "E-Type", year: 1963, trim: "Series 1 3.8 FHC", engineSize: "3.8L Inline-6", horsepower: 265, torque: 260, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 61200, exteriorColor: "Opalescent Silver Blue", interiorColor: "Dark Blue", doors: 2, seats: 2, bodyStyle: "Coupe" },
    condition: "excellent",
    status: "in-auction",
    description: "An early flat-floor Series 1 E-Type, restored to concours standard. Matching numbers, correct external bonnet latches, and a documented history file. Enzo Ferrari called it the most beautiful car ever made.",
    images: [
      img("1750957823101-87ec89cf6862", "Jaguar E-Type front", true),
      img("1611766424498-57b8418ed48d", "Jaguar E-Type coupe"),
    ],
    location: { city: "Greenwich", state: "CT", country: "US", zip: "06830" },
    seller: u3,
    features: ["Matching Numbers", "Flat-Floor Series 1", "Concours Restoration", "Moss 4-Speed", "Wire Wheels", "Complete History File"],
    reservePrice: 185000,
    startingPrice: 155000,
    estimatedValue: 210000,
    hasInspectionReport: true,
    hasFinancingOptions: true,
    views: 5620,
    watchlistCount: 389,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-22T12:00:00Z",
  },
  {
    id: "v-003",
    title: "1970 Chevrolet Chevelle SS 454",
    slug: "1970-chevrolet-chevelle-ss-454",
    spec: { make: "Chevrolet", model: "Chevelle", year: 1970, trim: "SS 454 LS6", engineSize: "7.4L V8", horsepower: 450, torque: 500, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 48900, exteriorColor: "Cranberry Red", interiorColor: "Black", vin: "136370B195420", doors: 2, seats: 5, bodyStyle: "Coupe" },
    condition: "excellent",
    status: "in-auction",
    description: "The king of muscle: a genuine LS6 Chevelle SS 454 with cowl induction and a Muncie 4-speed. Documented with build sheet, restored to factory specification in Cranberry Red with black stripes.",
    story: "Bought it off the original family in 2018. Everything was there — the build sheet, the protecto-plate, even the dealer paperwork. Restored it the right way.",
    images: [
      img("1584345274849-e9596d6ea12d", "Chevelle SS front", true),
    ],
    location: { city: "Nashville", state: "TN", country: "US", zip: "37201" },
    seller: u4,
    features: ["Genuine LS6", "Cowl Induction", "Muncie 4-Speed", "Build Sheet Documented", "12-Bolt Posi", "SS Bucket Interior"],
    reservePrice: 145000,
    startingPrice: 110000,
    estimatedValue: 160000,
    hasInspectionReport: true,
    hasFinancingOptions: false,
    views: 3210,
    watchlistCount: 201,
    createdAt: "2024-01-12T08:00:00Z",
    updatedAt: "2024-01-19T10:00:00Z",
  },
  {
    id: "v-004",
    title: "1972 Chevrolet Chevelle SS 396",
    slug: "1972-chevrolet-chevelle-ss-396",
    spec: { make: "Chevrolet", model: "Chevelle", year: 1972, trim: "SS 396", engineSize: "6.6L V8", horsepower: 375, torque: 415, fuelType: "gasoline", transmission: "automatic", driveType: "rwd", mileage: 63800, exteriorColor: "Sequoia Green", interiorColor: "Saddle", doors: 2, seats: 5, bodyStyle: "Coupe" },
    condition: "excellent",
    status: "in-auction",
    description: "Sequoia Green Chevelle SS 396 with factory air and a rebuilt TH400. Sharp older restoration that still shows beautifully. A usable, drivable classic muscle car.",
    images: [
      img("1698326456873-3f748646b8c3", "Chevelle SS 396 front", true),
    ],
    location: { city: "Chicago", state: "IL", country: "US", zip: "60601" },
    seller: u1,
    features: ["Factory Air", "Rebuilt TH400", "Cowl Induction Hood", "Rallye Wheels", "Power Steering", "Bench Seat"],
    reservePrice: 82000,
    startingPrice: 62000,
    estimatedValue: 92000,
    hasInspectionReport: true,
    hasFinancingOptions: true,
    views: 1890,
    watchlistCount: 98,
    createdAt: "2024-01-18T11:00:00Z",
    updatedAt: "2024-01-23T09:00:00Z",
  },
  {
    id: "v-005",
    title: "1967 Volkswagen Beetle 1500",
    slug: "1967-volkswagen-beetle-1500",
    spec: { make: "Volkswagen", model: "Beetle", year: 1967, trim: "1500 Deluxe", engineSize: "1.5L Flat-4", horsepower: 53, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 78400, exteriorColor: "Lotus White", interiorColor: "Tan", doors: 2, seats: 4, bodyStyle: "Coupe" },
    condition: "good",
    status: "active",
    description: "The one-year-only 1967 Beetle — the most collectible aircooled of them all. Restored in Lotus White with correct sloped headlights and single-year details. Runs and drives wonderfully.",
    images: [
      img("1768713533995-82ba685c1bc3", "Volkswagen Beetle front", true),
    ],
    location: { city: "Austin", state: "TX", country: "US", zip: "78701" },
    seller: u2,
    features: ["One-Year-Only 1967", "Correct Sloped Headlights", "Aircooled Flat-4", "4-Speed Manual", "Restored Interior", "Original Wheels"],
    startingPrice: 22000,
    estimatedValue: 28000,
    hasInspectionReport: false,
    hasFinancingOptions: true,
    views: 1420,
    watchlistCount: 67,
    createdAt: "2024-01-20T14:00:00Z",
    updatedAt: "2024-01-24T08:00:00Z",
  },
  {
    id: "v-006",
    title: "1969 Mercedes-Benz 280 SL Pagoda",
    slug: "1969-mercedes-benz-280-sl-pagoda",
    spec: { make: "Mercedes-Benz", model: "280 SL", year: 1969, trim: "Pagoda W113", engineSize: "2.8L Inline-6", horsepower: 170, torque: 177, fuelType: "gasoline", transmission: "automatic", driveType: "rwd", mileage: 71200, exteriorColor: "Horizon Blue", interiorColor: "Cream Leather", doors: 2, seats: 2, bodyStyle: "Convertible" },
    condition: "excellent",
    status: "in-auction",
    description: "An elegant W113 Pagoda in Horizon Blue over cream leather, with both the soft top and the iconic removable hardtop. Fuel-injected 2.8, beautifully sorted mechanically.",
    images: [
      img("1662282925500-ddd13acb4fef", "Mercedes 280 SL Pagoda", true),
    ],
    location: { city: "Miami", state: "FL", country: "US" },
    seller: u3,
    features: ["Both Tops Included", "Fuel Injected", "Becker Radio", "Chrome Wheels", "Documented Service", "Cream Leather Interior"],
    reservePrice: 135000,
    startingPrice: 110000,
    estimatedValue: 155000,
    hasInspectionReport: true,
    hasFinancingOptions: true,
    views: 4120,
    watchlistCount: 267,
    createdAt: "2024-01-08T09:00:00Z",
    updatedAt: "2024-01-21T14:00:00Z",
  },
  {
    id: "v-007",
    title: "1965 Shelby GT350",
    slug: "1965-shelby-gt350",
    spec: { make: "Ford", model: "Shelby GT350", year: 1965, trim: "Fastback", engineSize: "4.7L V8", horsepower: 306, torque: 329, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 42100, exteriorColor: "Wimbledon White", interiorColor: "Black", doors: 2, seats: 2, bodyStyle: "Fastback" },
    condition: "excellent",
    status: "active",
    description: "Wimbledon White GT350 with the signature Guardsman Blue stripes, side exhaust, and Cobra-branded valve covers. A raw, race-bred pony car with SAAC documentation.",
    images: [
      img("1727431682704-72149b5694cb", "Shelby GT350 race", true),
    ],
    location: { city: "Scottsdale", state: "AZ", country: "US" },
    seller: u2,
    features: ["SAAC Documented", "Guardsman Blue Stripes", "Side Exhaust", "Cobra Valve Covers", "4-Speed Manual", "Cragar Wheels"],
    startingPrice: 46000,
    estimatedValue: 54000,
    hasInspectionReport: false,
    hasFinancingOptions: true,
    views: 980,
    watchlistCount: 45,
    createdAt: "2024-01-22T10:00:00Z",
    updatedAt: "2024-01-24T12:00:00Z",
  },
  {
    id: "v-008",
    title: "1967 Jaguar E-Type Series 1 4.2 Roadster",
    slug: "1967-jaguar-e-type-series-1-42-roadster",
    spec: { make: "Jaguar", model: "E-Type", year: 1967, trim: "Series 1 4.2 OTS", engineSize: "4.2L Inline-6", horsepower: 265, torque: 283, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 55200, exteriorColor: "Old English White", interiorColor: "Black", doors: 2, seats: 2, bodyStyle: "Convertible" },
    condition: "excellent",
    status: "in-auction",
    description: "A desirable covered-headlight 4.2 roadster with the fully synchronized gearbox. Restored in Old English White with a black interior and correct chrome wire wheels.",
    images: [
      img("1655207297101-74aadf311205", "Jaguar E-Type roadster", true),
    ],
    location: { city: "Los Angeles", state: "CA", country: "US" },
    seller: u1,
    features: ["Covered Headlights", "Synchro Gearbox", "Chrome Wire Wheels", "Restored Convertible Top", "Matching Numbers Engine", "Tool Kit"],
    reservePrice: 189000,
    startingPrice: 152000,
    estimatedValue: 205000,
    hasInspectionReport: true,
    hasFinancingOptions: false,
    views: 2340,
    watchlistCount: 156,
    createdAt: "2024-01-14T08:30:00Z",
    updatedAt: "2024-01-21T11:00:00Z",
  },
  {
    id: "v-009",
    title: "1961 Jaguar E-Type Series 1 Roadster",
    slug: "1961-jaguar-e-type-series-1-roadster",
    spec: { make: "Jaguar", model: "E-Type", year: 1961, trim: "Series 1 3.8 OTS", engineSize: "3.8L Inline-6", horsepower: 265, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 48800, exteriorColor: "Gunmetal Grey", interiorColor: "Red", doors: 2, seats: 2, bodyStyle: "Convertible" },
    condition: "excellent",
    status: "upcoming",
    description: "An outside-bonnet-latch, flat-floor first-year E-Type — the holy grail of the breed. Believed to be one of the earliest export roadsters, with an extensively documented restoration.",
    images: [
      img("1557053946-2bddf5ae1c24", "Jaguar E-Type black roadster", true),
    ],
    location: { city: "New York", state: "NY", country: "US" },
    seller: u3,
    features: ["Outside Bonnet Latches", "Flat Floor", "First-Year Export Car", "Concours Restoration", "Welded Louvres", "Complete Provenance"],
    reservePrice: 285000,
    startingPrice: 240000,
    estimatedValue: 320000,
    hasInspectionReport: true,
    hasFinancingOptions: false,
    views: 6780,
    watchlistCount: 520,
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-23T10:00:00Z",
  },
  {
    id: "v-010",
    title: "1965 Aston Martin DB5",
    slug: "1965-aston-martin-db5",
    spec: { make: "Aston Martin", model: "DB5", year: 1965, engineSize: "4.0L Inline-6", horsepower: 282, torque: 288, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 39800, exteriorColor: "Silver Birch", interiorColor: "Black Connolly", doors: 2, seats: 4, bodyStyle: "Coupe" },
    condition: "excellent",
    status: "active",
    description: "The most famous grand tourer in the world, in classic Silver Birch over black Connolly leather. Triple SU carburettors, five-speed ZF gearbox, and a fully sorted mechanical package.",
    images: [
      img("1641035854263-797cec88bb8f", "Aston Martin DB5", true),
    ],
    location: { city: "Greenwich", state: "CT", country: "US" },
    seller: u3,
    features: ["Silver Birch Paint", "Connolly Leather", "ZF 5-Speed", "Triple SU Carbs", "Chrome Wire Wheels", "Matching Numbers"],
    startingPrice: 620000,
    estimatedValue: 780000,
    hasInspectionReport: true,
    hasFinancingOptions: true,
    views: 8640,
    watchlistCount: 612,
    createdAt: "2024-01-23T10:00:00Z",
    updatedAt: "2024-01-24T15:00:00Z",
  },
  {
    id: "v-011",
    title: "1970 Dodge Challenger R/T 440 Six Pack",
    slug: "1970-dodge-challenger-rt-440-six-pack",
    spec: { make: "Dodge", model: "Challenger", year: 1970, trim: "R/T", engineSize: "7.2L 440 Six Pack", horsepower: 390, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 68400, exteriorColor: "Sublime Green", interiorColor: "Black", doors: 2, seats: 5, bodyStyle: "Coupe" },
    condition: "good",
    status: "in-auction",
    description: "Sublime Green 1970 Challenger R/T with the rare 440 Six Pack option. Broadcast sheet present, Pistol Grip shifter, and an 8¾ rear end. A documented survivor with honest patina.",
    images: [
      img("1569679614220-975786cbaca7", "Dodge Challenger RT", true),
    ],
    location: { city: "Nashville", state: "TN", country: "US" },
    seller: u4,
    features: ["440 Six Pack", "Pistol Grip 4-Speed", "8¾ Dana Rear", "Broadcast Sheet", "Rallye Gauge Cluster", "Shaker Hood"],
    reservePrice: 118000,
    startingPrice: 95000,
    estimatedValue: 135000,
    hasInspectionReport: true,
    hasFinancingOptions: false,
    views: 2890,
    watchlistCount: 178,
    createdAt: "2024-01-11T09:00:00Z",
    updatedAt: "2024-01-20T13:00:00Z",
  },
  {
    id: "v-012",
    title: "1967 Chevrolet Corvette Sting Ray 427",
    slug: "1967-chevrolet-corvette-sting-ray-427",
    spec: { make: "Chevrolet", model: "Corvette", year: 1967, trim: "Sting Ray L71 427", engineSize: "7.0L V8", horsepower: 435, torque: 460, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 51600, exteriorColor: "Marlboro Maroon", interiorColor: "Black", doors: 2, seats: 2, bodyStyle: "Coupe" },
    condition: "excellent",
    status: "active",
    description: "The definitive C2: a 1967 Sting Ray with the tri-power L71 427. Marlboro Maroon over black, side pipes, and the iconic stinger hood. NCRS-documented and expertly restored.",
    images: [
      img("1581238159361-765c3090e72a", "Corvette Sting Ray", true),
    ],
    location: { city: "Houston", state: "TX", country: "US" },
    seller: u3,
    features: ["Tri-Power L71 427", "NCRS Documented", "Side Exhaust", "Stinger Hood", "4-Speed Muncie", "Knock-Off Wheels"],
    startingPrice: 148000,
    estimatedValue: 168000,
    hasInspectionReport: true,
    hasFinancingOptions: true,
    views: 1280,
    watchlistCount: 72,
    createdAt: "2024-01-19T12:00:00Z",
    updatedAt: "2024-01-24T11:00:00Z",
  },
  {
    id: "v-013",
    title: "1969 Jaguar E-Type Series 2 Coupe",
    slug: "1969-jaguar-e-type-series-2-coupe",
    spec: { make: "Jaguar", model: "E-Type", year: 1969, trim: "Series 2 4.2 FHC", engineSize: "4.2L Inline-6", horsepower: 246, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 58900, exteriorColor: "Regency Red", interiorColor: "Beige", doors: 2, seats: 2, bodyStyle: "Coupe" },
    condition: "good",
    status: "active",
    description: "A usable Series 2 fixed-head coupe in Regency Red, with improved cooling and better brakes. A driver-quality E-Type that's ready for tours and weekend blasts.",
    images: [
      img("1625942312259-d8570cc42444", "Jaguar E-Type Series 2", true),
    ],
    location: { city: "Phoenix", state: "AZ", country: "US" },
    seller: u2,
    features: ["Series 2 Cooling", "Uprated Brakes", "Chrome Wires", "Driver Quality", "Sorted Mechanicals", "Tonneau Cover"],
    startingPrice: 88000,
    estimatedValue: 104000,
    hasInspectionReport: false,
    hasFinancingOptions: true,
    views: 1540,
    watchlistCount: 93,
    createdAt: "2024-01-21T14:00:00Z",
    updatedAt: "2024-01-24T10:00:00Z",
  },
  {
    id: "v-014",
    title: "1966 Jaguar E-Type Series 1 Roadster",
    slug: "1966-jaguar-e-type-series-1-roadster",
    spec: { make: "Jaguar", model: "E-Type", year: 1966, trim: "Series 1 4.2 OTS", engineSize: "4.2L Inline-6", horsepower: 265, torque: 283, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 46300, exteriorColor: "Carmen Red", interiorColor: "Black", doors: 2, seats: 2, bodyStyle: "Convertible" },
    condition: "excellent",
    status: "in-auction",
    description: "Carmen Red 4.2 roadster with covered headlights and a recent cosmetic restoration. Presents beautifully and drives even better — the quintessential open E-Type.",
    images: [
      img("1753266322092-3199ec27c087", "Jaguar E-Type red roadster", true),
    ],
    location: { city: "Portland", state: "OR", country: "US" },
    seller: u1,
    features: ["Covered Headlights", "Recent Restoration", "Chrome Wire Wheels", "New Convertible Top", "Rebuilt Carbs", "Stainless Exhaust"],
    reservePrice: 172000,
    startingPrice: 138000,
    estimatedValue: 195000,
    hasInspectionReport: true,
    hasFinancingOptions: true,
    views: 2120,
    watchlistCount: 134,
    createdAt: "2024-01-13T10:30:00Z",
    updatedAt: "2024-01-22T16:00:00Z",
  },
  {
    id: "v-015",
    title: "1965 Jaguar E-Type Series 1 4.2 Coupe",
    slug: "1965-jaguar-e-type-series-1-42-coupe",
    spec: { make: "Jaguar", model: "E-Type", year: 1965, trim: "Series 1 4.2 FHC", engineSize: "4.2L Inline-6", horsepower: 265, fuelType: "gasoline", transmission: "manual", driveType: "rwd", mileage: 53400, exteriorColor: "Opalescent Silver", interiorColor: "Red", doors: 2, seats: 2, bodyStyle: "Coupe" },
    condition: "excellent",
    status: "upcoming",
    description: "A superb 4.2 fixed-head coupe with the more comfortable seats and all-synchro gearbox. Opalescent Silver over red, matching numbers, and a thick history file.",
    images: [
      img("1611766424498-57b8418ed48d", "Jaguar E-Type silver coupe", true),
    ],
    location: { city: "San Jose", state: "CA", country: "US" },
    seller: u2,
    features: ["Matching Numbers", "All-Synchro Gearbox", "Improved Seats", "Chrome Wires", "History File", "Recent Service"],
    reservePrice: 165000,
    startingPrice: 140000,
    estimatedValue: 188000,
    hasInspectionReport: true,
    hasFinancingOptions: false,
    views: 6780,
    watchlistCount: 520,
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-23T10:00:00Z",
  },
];

export function getMockVehicle(id: string): Vehicle | undefined {
  return MOCK_VEHICLES.find((v) => v.id === id);
}

export function getMockVehicleBySlug(slug: string): Vehicle | undefined {
  return MOCK_VEHICLES.find((v) => v.slug === slug);
}
